from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "<eRlfIMZzGqBbmn2hqXinHxSx>"

# Found in the 'Manage Deployment' page
CLOUD_ID = "FoodDB:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQxYWI0M2Q3OWRhNGQ0ZTY4YjA5MjEzN2Y0YTI4YzcyOSQ3NjM4NjRjYzUxMDA0MjQwYjhjNmJmMDRlOTIzYmE4OQ=="

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
client.info()
# {'name': 'instance-0000000000', 'cluster_name': ...}